### ISSUE TITLE
Orange gone?

### ISSUE THREAD

**Issue by derickr** [james2doyle/xdebug-devtools#1]
I like this! I am less keen on the lovely orange colours in the header having disappeared ;-)

(Sorry, I realise this is not a real issue, but couldn't find another way to contact you).

Is there anything on the xdebug side to make this easier?

**Comment by james2doyle** [comment]
Thanks. Are you asking why the default styling is gone? or why the error is no longer in the body of the page?

**Comment by derickr** [comment]
The former - The second one is part of the feature set I thought?

In any case, I am just being pedantic as I like the orange colour I chose for Xdebug :-)

**Comment by james2doyle** [comment]
I restyled the table to make it easier to read and more color coded to the PHP.net website. 

It could be an option at some point to toggle off

**Comment by james2doyle** [comment]
I added options for everything you mentioned

https://github.com/james2doyle/xdebug-devtools#options
